#!/usr/bin/env bash
usage() {
	echo "This compilation script requires $REQUIRED_ARGUMENTS positional arguments to run."
	echo -e "Only $# of the $REQUIRED_ARGUMENTS were provided.\n"
	echo "Usage: build [tokenizer|test|all]"
}

compile_tokenizer() {
	gcc -c tokenizer.c -o tokenizer.o
}

compile_runner() {
	gcc tokenize.c tokenizer.o -o tokenize 
}

compile_all() {
	compile_tokenizer
	compile_runner
}

if [[ $# -lt $REQUIRED_ARGUMENTS ]]; then
	usage
fi

echo -e "Compiling target \"$1\"..."
case "$1" in
	"tokenizer" | "lib" | "library")
		if compile_tokenizer ; then 
			echo "Compilation succeeded."
		else
			echo "Compilation failed."
		fi
		;;

	"tokenize" | "runner")
		if compile_runner ; then 
			echo "Compilation succeeded."
		else
			echo "Compilation failed."
		fi
		;;
	
	"all")
		if compile_all ; then
			echo "Compilation succeeded."
		else
			echo "Compilation failed."
		fi
		;;

	*)  
		echo -e "Build target \"$1\" is invalid.\n"
		usage

esac
